apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: lil-eks
  region: us-east-1

  tags:
    project: linkedin-learning

nodeGroups:
  - name: worker-node
    instanceType: t2.micro
    desiredCapacity: 2
availabilityZones: ["us-east-1a", "us-east-1b"]
